// Real NYC trip data, parsed from the uploaded itinerary
window.TRIP_DEFAULT = {
  title: 'New York',
  subtitleKo: '뉴욕 · 10일',
  dates: 'May 4 — May 13, 2025',
  travelers: 'Solo trip',
  hotel: 'Kimpton Theta New York (Times Square)',
  hotels: [
    {
      name: 'Kimpton Theta New York',
      area: 'Times Square',
      checkin: 'May 4, 2025',
      checkinTime: '15:00',
      checkout: 'May 9, 2025',
      checkoutTime: '12:00',
      nights: 5,
      price: '$289/박',
      address: '125 W 48th St, New York, NY 10036',
      phone: '+1 212-354-2323',
      confirmation: '73378565985208',
      amenities: ['Free WiFi', 'Fitness Center', 'Pet Friendly', 'Bar', '24h Front Desk'],
      note: '타임스퀘어에서 도보 3분. 체크인 15시, 체크아웃 12시. 프론트에서 룸 업그레이드 요청 가능.',
      rating: 4.3,
      hue: 25,
    },
    {
      name: 'Royal Sonesta Washington DC Capitol Hill',
      area: 'Capitol Hill, D.C.',
      checkin: 'May 9, 2025',
      checkinTime: '16:00',
      checkout: 'May 11, 2025',
      checkoutTime: '11:00',
      nights: 2,
      address: '20 Massachusetts Ave NW, Washington, DC 20001',
      phone: '+1 202-888-1850',
      confirmation: '73392131862879',
      amenities: ['Free WiFi', 'Fitness Center', 'Restaurant', 'Bar', 'Pet Friendly', 'Valet Parking'],
      note: '체크인 16시, 체크아웃 11시. 캐피톨 힐 인근. 발레파킹 가능.',
      rating: 4.0,
      hue: 200,
    },
    {
      name: 'Hotel RIU Plaza Manhattan Times Square',
      area: 'Times Square',
      checkin: 'May 11, 2025',
      checkinTime: '15:00',
      checkout: 'May 14, 2025',
      checkoutTime: '12:00',
      nights: 3,
      address: '145 W 47th St, New York, NY 10036',
      phone: '+1 646-864-1100',
      confirmation: '73382367193804',
      amenities: ['Free WiFi', 'Fitness Center', 'Restaurant', 'Bar', 'Free Breakfast', 'Business Center'],
      note: '체크인 15시, 체크아웃 12시. 조식 포함. 타임스퀘어 도보 1분.',
      rating: 4.0,
      hue: 40,
    },
  ],
  days: [
    {
      n: 1, date: 'May 4', weekday: 'Mon',
      title: '도착, 타임스퀘어',
      titleEn: 'Arrival & Midtown',
      hero: { hue: 25, label: 'TIMES SQUARE' },
      weather: '맑음 · 18°',
      items: [
        { time: '10:00', cat: 'flight', title: 'JFK 공항 도착',   en: 'Arrive at JFK Airport', loc: 'JFK International',
          note: '지하철로 이동\n맨해튼까지 60분\nair train(엘리베이터level 2)-jamaica station(빨간색방향)-내려서 엘리베이터로L2층(Concourse)- 에어트레인 이용료8.25달러결제-표지판: 머리 위에 있는 \'Subway E J Z\'-엘리베이터 위치: 보통 계단 옆쪽이나 구석에 \'Elevator to E Train\' 표지판-엘리베이터\'Lower Level (E Train Platform)\' 버튼-(탑승전3달러결제)E선 열차 탑승-방향 확인: \'Manhattan Bound\' 또는 \'World Trade Center\' 행이라고 적힌 전광판-E선(파란색 동그라미)-40분 걸려50th Street 역 도착-지상' },
        { time: '14:00', cat: 'hotel',  title: '호텔 짐 맡기기',    en: 'Kimpton Theta New York', loc: 'Times Square by IHG',
          note: '체크인/프론트에 짐 맡기기\n"Hi, I\'m a bit early for check-in. Is it possible to leave my luggage here for a while?"' },
        { time: '14:30', cat: 'food',   title: '점심: 피자 or 타코', en: "Joe's Pizza / Los Tacos No.1", loc: 'Midtown',
          note: "Joe's Pizza (뉴욕 정통 조각 피자)\nLos Tacos No.1 (타코 맛집)", price: '$' },
        { time: '15:30', cat: 'sight',  title: '뉴욕 공립 도서관',   en: 'New York Public Library', loc: '5th Ave @ 42nd',
          note: '도서관 입구의 두마리 사자상(인내, 용기)\n1층 아스토 홀(Astor Hall)\n1층 treasures exhibition트레저스 엑시비션:구텐바르크 성경, 토마스 제퍼슨의 \'독립선언서\' 사본, 찰스디킨스의 필기구..\n맥그로우 로툰다(McGraw Rotunda): 로즈 메인 리딩 룸 들어가기전 웅장한 중앙 홀\n3층 Rose Main Reading Room(인셉션, 투모로우 배경) \n로즈 메인 리딩 룸 이용 팁:리딩 룸 입구는 두 곳입니다. 하나는 관광객용(사진만 찍고 나가는 곳), 하나는 이용자용(Study & Research)입니다\n입구에서 보안 요원이 "Visiting or Studying?"이라고 물을 수 있습니다. 이때 "Studying" 혹은 "Reading"이라고 답하고 \n안쪽으로 들어가 빈자리에 앉으시면 됩니다. I\'m here for quiet study/reading이라고 대답하기\n퇴실은 5시 45분쯤', duration: '1h 30m' },
        { time: '17:30', cat: 'hotel',  title: '호텔 체크인',       en: 'Hotel Check-in', loc: 'Kimpton Theta', _hotelRef: 'Kimpton Theta New York' },
        { time: '19:30', cat: 'show',   title: 'Top View 야경 버스', en: 'Top View Night Bus Tour', loc: "M&M's World 앞",
          note: "타임스퀘어 (M&M's World 앞출발)\n타임스퀘어-크라이슬러,공립도서관-플랫아이언-워싱턴스퀘어파크-브루클린브릿지(90분)", price: '$29–44', duration: '90m' },
        { time: '21:30', cat: 'food',   title: '저녁: Chick-fil-A',  en: 'Chick-fil-A', loc: 'Midtown',
          note: 'Chick-fil-A칙필레버거: Chick-fil-A Chicken Sandwich meal, deluxe(+토마토치즈양배추), \n감자튀김 찍어먹을 소스부탁 can i get all the sauces, please?\n칙필레미니사이즈소스:8oz(2.9달러+tax=3.25달러)', price: '$' },
      ],
    },
    {
      n: 2, date: 'May 5', weekday: 'Tue',
      title: '자유의 여신상, 덤보',
      titleEn: 'Liberty & Downtown',
      hero: { hue: 210, label: 'LIBERTY CRUISE' },
      weather: '흐림 · 16°',
      items: [
        { time: '09:30', cat: 'ferry',  title: '다운타운 리버티 크루즈', en: 'Downtown Liberty Cruise', loc: 'Pier 16 · 167 John St',
          note: '호텔에서 지하철타고 풀턴 스트리트 서브웨이 스테이션\npier16탑승(Pier 16,167 John St, New York, NY 10038):자유의여신상-브루클린 브릿지뷰(60분)\n스케줄: 오전 10시, 11시 30분, 13시, 14시 30분', price: '₩27,945', duration: '60m' },
        { time: '11:30', cat: 'walk',   title: '배터리 파크',          en: 'Battery Park', loc: 'Lower Manhattan',
          note: '자유의 여신상 보이는 공원' },
        { time: '12:15', cat: 'sight',  title: '월스트리트',           en: 'Wall Street', loc: 'Financial District',
          note: '황소상, 뉴욕 증권거래소 구경' },
        { time: '13:30', cat: 'food',   title: '점심',                en: 'Lunch — FiDi', loc: 'Financial District', price: '$$' },
        { time: '14:30', cat: 'sight',  title: '9/11 메모리얼 & Oculus', en: '9/11 Memorial + One WTC', loc: '180 Greenwich St',
          note: '세계무역센터 부지 및 911메모리얼 파크\n911메모리얼파크:쌍둥이 빌딩 자리에 만들어진 추모공원\n원월드트레이드센터(무너진 건물을 대신해 그 옆에 새로 생긴 미국에서 가장 높은 빌딩)\n오큘러스(기차역, 쇼핑몰)' },
        { time: '16:00', cat: 'view',   title: '덤보 — 맨해튼 브리지 뷰', en: 'DUMBO / 35 Washington St', loc: 'Brooklyn',
          note: '주소: 35 Washington St, Brooklyn, NY11201\nWTC 근처의 Chambers St Station (또는 Fulton St Station)에서 A 또는 C 라인 Downtown & Brooklyn 방면 열차-High St - Brooklyn Bridge Station에서 내리기' },
        { time: '16:30', cat: 'food',   title: "Juliana's Pizza",      en: "Juliana's Pizza", loc: 'DUMBO',
          note: '줄리아나 피자: 하프앤하프, 마리게리타+화이트조합', price: '$$' },
        { time: '17:30', cat: 'walk',   title: '브루클린 브리지 도보',  en: 'Brooklyn Bridge Walk', loc: 'Brooklyn → Manhattan',
          note: '워싱턴 스트리트에서 위쪽(남쪽) 언덕 방향으로 2분만→구글 맵에 "Brooklyn Bridge Underpass" 혹은 "Washington St Stairway"라고 검색\n계단을 따라 올라가면 바로 브루클린 브릿지의 보행자 전용도로Wooden Walkway연결\n맨해튼 스카이라인 보면서 30-40분 걷기\nCity Hall 역에서 N, R, W선 (노란색 라인) 탑승 42 St - Times Sq 역 하차(15분 소요)', duration: '40m' },
        { time: '19:30', cat: 'food',   title: '저녁',                 en: 'Dinner', loc: 'Midtown' },
      ],
    },
    {
      n: 3, date: 'May 6', weekday: 'Wed',
      title: 'MoMA와 록펠러',
      titleEn: 'MoMA & Rockefeller',
      hero: { hue: 45, label: 'ROCKEFELLER PLAZA' },
      weather: '맑음 · 19°',
      items: [
        { time: '10:00', cat: 'sight',  title: 'MoMA',                 en: 'Museum of Modern Art', loc: '11 W 53rd St',
          note: '오픈런 입장→무료 한국어 오디오 가이드(모마 내 와이파이 접속)\n5층부터 내려오기*(5층: 고흐의 별이 빛나는 밤, 피카소의 아비뇽의 여인들, 모네의 수련)\n4층 앤디워홀의 캠벨 수프 캔\n1층 야외정원Abby Aldrich Rockefeller Sculpture Garden\n굿즈 구입: 모자', duration: '2h 30m' },
        { time: '13:00', cat: 'food',   title: "Gallagher's 스테이크",  en: "Gallagher's Steakhouse", loc: 'Midtown',
          note: '갤러거 스테이크 하우스\nLunch Special Menu 3-Course Lunch Menu로 운영되며, 에피타이저 + 메인(Sliced Filet Mignon) + 디저트가 포함\n물은 tap water(수돗물 무료), bottled water(유료) 선택\n에피타이저는 시저샐러드, 클램차우더수프/메인은 Sliced Filet Mignon, 10 oz. Filet Mignon/디저트는 뉴욕치즈케이크, 아이스크림\n식사후 영수증 요청→팁 선택→최종금액을 적어 서명과 함께 카드를 두면→결제 후 카드 돌려줌 ', price: '$$$$', duration: '1h 30m' },
        { time: '15:00', cat: 'walk',   title: '5번가 산책',           en: '5th Avenue Stroll', loc: '5th Ave',
          note: '세인트 패트릭 대성당 내부관람, 웅장한 고딕양식' },
        { time: '16:00', cat: 'sight',  title: '그랜드 센트럴',         en: 'Grand Central Terminal', loc: '89 E 42nd St',
          note: '세계 최대 기차역' },
        { time: '17:00', cat: 'walk',   title: '록펠러 플라자',         en: 'Rockefeller Center Plaza', loc: 'Midtown',
          note: '탑오브더락 입장전 주변구경' },
        { time: '18:30', cat: 'view',   title: 'Top of the Rock',      en: 'Top of the Rock Observatory', loc: 'Rockefeller Center',
          note: '일몰 1시간 전 입장(+야경 감상), 엠파이어빌딩 뷰', price: '₩64,490' },
        { time: '21:00', cat: 'food',   title: '저녁',                 en: 'Dinner', loc: 'Midtown' },
      ],
    },
    {
      n: 4, date: 'May 7', weekday: 'Thu',
      title: '메트로폴리탄, 클로이스터',
      titleEn: 'The Met & Cloisters',
      hero: { hue: 340, label: 'THE MET · 5TH AVE' },
      weather: '맑음 · 21°',
      items: [
        { time: '10:00', cat: 'sight',  title: 'The Met',               en: 'Metropolitan Museum of Art', loc: '1000 5th Ave',
          note: '10시 개장과 동시 입장추천, 200만점의 작품이 있어 선택과 집중이 핵심\n정문에 도착하면 줄이 두갈래 \'General Admission\' 혹은 \'Timed Entry\' 줄에 서세요. (예약자는 줄이 훨씬 빨리 빠짐)\n보안검색(가방검사)후 입구의 검표 직원에게 휴대폰의 QR 코드를 보여주면 바로 입장 가능\n1층 이집트 미술(The Egyptian Art): 로비 오른쪽, 덴두르 신전Temple of Dendur은 꼭 봐야함, 나는 전설이다 배경\n1층 아메리카 윙(The American Wing)\n2층 유럽 회화 (European Paintings): 고흐, 모네, 르누아르, 베르메르 걸작\n4층 루프탑 가든(The Cantor Roof Garden): 전망대 겸 카페\n박물관계단(미드 가십걸)에서 사진 찍기', price: '$30', duration: '3h' },
        { time: '13:30', cat: 'food',   title: '점심',                  en: 'Lunch', loc: 'UES' },
        { time: '15:00', cat: 'sight',  title: 'The Met Cloisters',     en: 'Met Cloisters', loc: 'Fort Tryon Park',
          note: '메트 정문에서 나와 81가(81st St)를 따라 서쪽(센트럴 파크 방향)으로 쭉 가로지르기\n→자연사 박물관 옆에 있는 81 St-Museum of Natural History 역→지하철 탑승 (A선 Blue)\nA선(Uptown & 207 St 방향)ⁿ-A선(익스프레스)타기 →190 St 역(엘리베이터 타고 올라오기)\n지하철에서 내리면 개찰구 쪽 말고, Fort Tryon Park라고 써진 이정표를 따라가서 아주 큰 엘리베이터를 타기\n엘베로 지상 도착하면 바로 공원 입구와 연결→공원 길 걷기 Margaret Corbin Drive여기서부터 클로이스터스 성채까지 약 10~15분\n메트로폴리탄 미술관의 분관, 프랑스식수도원건물, 메트 당일 티켓있으면 무료관람\n폰트브로아 수도원 중정Cuxa Cloister - ★필수 코스:클로이스터스 상징\n폰트브로아 수도원 중정 (Cuxa Cloister) - ★필수 코스\n유니콘 태피스트리 방 (The Unicorn Tapestries) - ★최고의 걸작\n메로드 제단화 (Mérode Altarpiece) & 장식 예술\n허드슨 강 뷰 테라스 (Bonnefont Cloister & Trie Cloister)\n다시 호텔(킴튼 세타)로 돌아올 때는 A선 지하철을 타고 한 번에 42 St-Port Authority Bus Terminal역 하차' },
        { time: '18:30', cat: 'food',   title: '저녁',                  en: 'Dinner', loc: 'Midtown' },
      ],
    },
    {
      n: 5, date: 'May 8', weekday: 'Fri',
      title: '자연사 박물관, 센트럴파크',
      titleEn: 'AMNH & Central Park',
      hero: { hue: 120, label: 'CENTRAL PARK' },
      weather: '맑음 · 22°',
      items: [
        { time: '09:30', cat: 'sight',  title: '자연사 박물관',          en: 'American Museum of Natural History', loc: 'Upper West Side',
          note: '1층 밀스타인 해양 생물관:천장에 매달린 실물 크기의 대왕고래(Blue Whale)모형\n77가(77th St) 쪽 출구로 나오시는 것이 좋습니다.', price: '$25', duration: '2h' },
        { time: '12:30', cat: 'food',   title: '점심: 피크닉 준비',       en: 'Levain + Chipotle (to go)', loc: 'UWS',
          note: 'levain bakery르뱅쿠키\nchipotle치폴레: 보울 포장', price: '$' },
        { time: '13:30', cat: 'walk',   title: '센트럴 파크',            en: 'Central Park', loc: 'Manhattan',
          note: '십 미도우sheep meadow잔디밭: 피크닉\n더몰: 십 미도우 바로 옆, 느티나무 가로수길\n베데스타 테라스Bethesda Terrace&분수: 더 몰 끝부분, 계단 아래 분수 천장 타일 장식\n체리힐Cherry Hill\n보우브리지Bow Bridge: 하얀색 곡선 다리, 로맨틱한 포토존', duration: '3h' },
        { time: '18:00', cat: 'food',   title: 'The Halal Guys',        en: 'The Halal Guys', loc: '53rd & 6th Ave',
          note: '할랄 가이즈The Halal Guys, 화이트 소스는 듬뿍, 레드 소스는 조금', price: '$' },
      ],
    },
    {
      n: 6, date: 'May 9', weekday: 'Sat',
      title: '워싱턴 D.C. 이동',
      titleEn: 'Travel to D.C.',
      hero: { hue: 200, label: 'WASHINGTON D.C.' },
      weather: '맑음 · 20°',
      items: [
        { time: '09:00', cat: 'flight', title: 'D.C.로 이동',            en: 'Travel to Washington D.C.', loc: 'NYC → D.C.' },
        { time: '13:00', cat: 'hotel',  title: 'D.C. 호텔 체크인',       en: 'D.C. Hotel', loc: 'Washington D.C.',
          note: '짐 맡기기 또는 체크인', _hotelRef: 'D.C. Hotel' },
        { time: '14:30', cat: 'sight',  title: '국립 자연사 박물관',      en: 'National Museum of Natural History', loc: 'The Mall, D.C.',
          note: '무료 입장' },
        { time: '19:00', cat: 'food',   title: '저녁',                   en: 'Dinner', loc: 'D.C.' },
      ],
    },
    {
      n: 7, date: 'May 10', weekday: 'Sun',
      title: '워싱턴 기념물 투어',
      titleEn: 'D.C. Monuments',
      hero: { hue: 50, label: 'THE NATIONAL MALL' },
      weather: '맑음 · 24°',
      items: [
        { time: '09:00', cat: 'sight',  title: '워싱턴 기념탑',           en: 'Washington Monument', loc: 'The Mall',
          note: '공식 사이트 예약 (30일 전 오전 10시 ET, 수수료 $1)', price: '$1' },
        { time: '10:30', cat: 'sight',  title: '2차 세계대전 기념관',      en: 'WWII Memorial', loc: 'The Mall',
          note: '편한 신발 필수' },
        { time: '11:15', cat: 'sight',  title: '리플렉팅 풀 & 링컨 기념관', en: 'Reflecting Pool & Lincoln Memorial', loc: 'The Mall',
          note: '물병 챙기기' },
        { time: '12:30', cat: 'sight',  title: '한국전쟁 기념관',          en: 'Korean War Veterans Memorial', loc: 'The Mall',
          note: '선글라스' },
        { time: '13:30', cat: 'food',   title: '점심',                   en: 'Lunch', loc: 'D.C.',
          note: '모자 · 선크림' },
        { time: '15:00', cat: 'sight',  title: '국립 항공우주 박물관',     en: 'National Air and Space Museum', loc: 'The Mall' },
        { time: '17:30', cat: 'sight',  title: '국회 의사당',             en: 'U.S. Capitol Building', loc: 'D.C.' },
      ],
    },
    {
      n: 8, date: 'May 11', weekday: 'Mon',
      title: '뉴욕 복귀, 브라이언트 파크',
      titleEn: 'Back to NYC',
      hero: { hue: 100, label: 'BRYANT PARK' },
      weather: '부분 흐림 · 19°',
      items: [
        { time: '09:30', cat: 'walk',   title: 'D.C. 오전 일정',          en: 'Morning in D.C.', loc: 'D.C.' },
        { time: '13:00', cat: 'flight', title: '뉴욕으로 이동',            en: 'Travel back to NYC', loc: 'D.C. → NYC' },
        { time: '17:30', cat: 'walk',   title: '브라이언트 파크',          en: 'Bryant Park', loc: 'Midtown',
          note: '느긋한 오후' },
        { time: '19:00', cat: 'food',   title: '북창동 순두부',            en: 'Bookchang-dong Soondubu', loc: 'K-Town',
          note: '순두부찌개 + LA갈비', price: '$$' },
      ],
    },
    {
      n: 9, date: 'May 12', weekday: 'Tue',
      title: 'Vessel, 하이라인, 빌리지',
      titleEn: 'Hudson Yards & Village',
      hero: { hue: 280, label: 'THE VESSEL' },
      weather: '맑음 · 22°',
      items: [
        { time: '09:00', cat: 'view',   title: 'Vessel',                en: 'Vessel · Hudson Yards', loc: '34 St–Hudson Yards',
          note: '호텔에서 7번가/42가 방향으로 5분만 걸어가면 Times Sq-42 St 역\n7번 노선(보라색)을 타고 종점인 34 St-Hudson Yards 역에서 하차 (한 정거장, 3분 소요)\n황금빛 벌집 모양\n쇼핑몰The Shops at Hudson Yards 4층 창가에서 베슬을 위에서 내려다보는 구도 사진(화장실 이용 추천!)' },
        { time: '09:45', cat: 'walk',   title: 'The High Line',         en: 'The High Line', loc: 'Chelsea',
          note: '공중정원, 버려진 철길\n베슬 바로 옆에 하이라인 시작점 입구', duration: '1h' },
        { time: '11:00', cat: 'view',   title: 'Little Island',          en: 'Little Island', loc: 'Hudson River',
          note: '허드슨 강 위에 뜬 콘크리트 튤립섬\n인공섬, 섬꼭대기 전망대에서 엠파이어 스테이트 빌딩과 원 월드 트레이드 센터 뷰' },
        { time: '12:30', cat: 'food',   title: 'Chelsea Market 점심',    en: 'Chelsea Market', loc: '75 9th Ave',
          note: '로스 타코스Los Tacos No.1\n랍스터 플레이스 Lobster Place', price: '$$' },
        { time: '14:30', cat: 'walk',   title: '그리니치 빌리지',         en: 'Greenwich Village', loc: 'West Village',
          note: '뉴욕감성골목, 로맨틱한 분위기, 여유로운 산책\n미드의 배경지:프렌즈, 섹스앤더시티\n워싱턴 스퀘어 파크에서 매그놀리아 바나나 푸딩먹기' },
        { time: '16:00', cat: 'shop',   title: 'Harry Potter Store',     en: 'Harry Potter NY', loc: 'Flatiron',
          note: '화장실 있음' },
        { time: '16:45', cat: 'shop',   title: 'Fishs Eddy',             en: 'Fishs Eddy', loc: 'Flatiron',
          note: '귀여운 소품샵(자유여신상 컵)', price: '$$' },
        { time: '19:00', cat: 'food',   title: '저녁',                   en: 'Dinner', loc: 'Midtown' },
        { time: '20:00', cat: 'show',   title: '재즈 or 뮤지컬',          en: 'Jazz Show or Musical', loc: 'Broadway',
          note: '현장구매또는TKTS또는뮤지컬로타리에서 예매(알라딘 / 라이온킹 / 위키드 / 시카고)', price: '$$$' },
      ],
    },
    {
      n: 10, date: 'May 13', weekday: 'Wed',
      title: '마지막 날, 쇼핑',
      titleEn: 'Souvenirs & Farewell',
      hero: { hue: 0, label: 'TIMES SQUARE' },
      weather: '맑음 · 20°',
      items: [
        { time: '09:30', cat: 'shop',   title: '타임스퀘어 기념품',       en: 'Times Square Souvenirs', loc: 'Midtown',
          note: "Disney Store, M&M, Hershey's Chocolate World에서 기념품사기" },
        { time: '11:30', cat: 'walk',   title: '센트럴파크 벨베데어',      en: 'Central Park — Belvedere Castle', loc: 'Central Park',
          note: '벨베데레성Belvedere Castle' },
        { time: '13:00', cat: 'food',   title: '점심',                   en: 'Lunch', loc: 'Midtown' },
        { time: '14:30', cat: 'walk',   title: '브라이언트 파크',         en: 'Bryant Park', loc: 'Midtown' },
        { time: '15:30', cat: 'shop',   title: 'Whole Foods',            en: 'Whole Foods Market', loc: 'Midtown' },
        { time: '16:15', cat: 'shop',   title: 'CVS',                    en: 'CVS Pharmacy', loc: 'Midtown',
          note: '리스테린 쿨민트필름3개세트$6.99, NATROL멜라토닌젤리5mg60개$11', price: '$' },
        { time: '16:45', cat: 'shop',   title: 'Target',                 en: 'Target', loc: 'Midtown',
          note: '너즈젤리, 소화제TUMS$7', price: '$' },
        { time: '17:30', cat: 'shop',   title: "Trader Joe's",           en: "Trader Joe's", loc: 'Midtown',
          note: '프레첼$4.20, 핸드크림, 손소독제, 레몬커드$3.99, 버터아몬드씬$3.3, 메이플피칸그래놀라시리얼, 엑스트라버진올리브오일스프레이', price: '$' },
        { time: '19:30', cat: 'food',   title: '마지막 저녁',             en: 'Farewell Dinner', loc: 'Midtown' },
      ],
    },
  ],

  // Preparation (from sheet 1)
  prep: {
    checklist: [
      '항공권 예매', '숙소 예매', 'ESTA 신청', '짐 싸기',
      '로밍/유심 준비', 'Uber 앱 설치', '여행자 보험', '빅버스 예매',
      '공항 셔틀 예매',
    ],
    docs: [
      'ESTA 승인', '왕복 항공권', '호텔 바우처', '재직증명서(영문)',
    ],
    pack: [
      '피크닉 매트', '물티슈', '휴대용 비데', '위생 장갑',
    ],
  },

  // Food guide (from sheet 3)
  food: [
    { cat: '🍕 Pizza',    name: "Joe's Pizza",             detail: '클래식 NY 슬라이스',                                    price: '$',       note: '맨해튼 여러 지점' },
    { cat: '🍕 Pizza',    name: "Juliana's Pizza",          detail: 'Half-and-half: Margherita + White',                      price: '$$',      note: '덤보, 브루클린' },
    { cat: '🥯 Bagel',    name: 'Essa Bagel',               detail: 'Everything bagel + cream cheese + smoked salmon',        price: '$18–25',  note: '' },
    { cat: '🥯 Bagel',    name: 'Apollo Bagels',            detail: '갓 구운 베이글',                                         price: '$',       note: '' },
    { cat: '🥯 Bagel',    name: 'Pop Up Bagel',             detail: '베이글 3개 $13 (크림치즈 1개 포함)',                     price: '$13',     note: '' },
    { cat: '🌮 Tacos',    name: 'Los Tacos No.1',           detail: 'NYC 최고 타코 · al pastor 또는 carne asada',             price: '$$',      note: '첼시 마켓 외' },
    { cat: '🍔 Burger',   name: 'Chick-fil-A',              detail: 'Deluxe Meal · "Can I get all the sauces, please?"',      price: '$12–15',  note: '일요일 휴무' },
    { cat: '🍔 Burger',   name: "Tony Dragon's Grille",     detail: 'Tony Burger $13 / Beef & Portobello $14 · 위생장갑 요청', price: '$13–14',  note: '10AM–6PM (푸드트럭)' },
    { cat: '🥩 Steak',    name: "Gallagher's Steakhouse",   detail: '3코스 런치: 애피 + Sliced Filet Mignon + NY 치즈케익',   price: '$$$$',    note: '구글 예약 필요' },
    { cat: '🌯 Fast',     name: 'Chipotle',                 detail: '보울: 라이스 + 빈 + 단백질 + 토핑 올 + 과카 (+$3)',       price: '$21.50',  note: '라이스에 고수 있음' },
    { cat: '🌯 Fast',     name: 'The Halal Guys',           detail: '라이스 플레이트 or 랩 · 화이트 많이, 레드 조금',          price: '$',       note: '53rd & 6th Ave' },
    { cat: '🦞 Seafood',  name: 'Lobster Place',            detail: '신선한 랍스터 롤',                                       price: '$$',      note: '첼시 마켓 내부' },
    { cat: '🍲 Korean',   name: '북창동 순두부',             detail: '순두부찌개 + LA갈비',                                    price: '$$',      note: 'K-타운' },
    { cat: '🍪 Dessert',  name: 'Levain Bakery',            detail: '초코칩 월넛 쿠키 (수상작) · 레몬도 추천',                 price: '$',       note: '뜨끈하고 큼직' },
    { cat: '🍪 Dessert',  name: 'Magnolia Bakery',          detail: '바나나 푸딩 → 워싱턴 스퀘어 파크',                        price: '$',       note: '' },
    { cat: '🍪 Dessert',  name: "Junior's Cheesecake",      detail: '오리지널 NY 치즈케익',                                   price: '$',       note: '타임스퀘어/그랜드센트럴' },
    { cat: '☕ Dessert',  name: "Ralph's Coffee",           detail: '말차 라떼',                                              price: '$',       note: '랄프로렌 플래그십 내부' },
  ],
};

// ─── Rome & Florence & Assisi — 11일 샘플 ─────────────────────
window.ROME_DEFAULT = {
  title: 'Rome & Florence',
  subtitleKo: '로마·피렌체·아씨시 · 11일',
  dates: 'Oct 5 — Oct 15, 2025',
  travelers: 'Solo trip',
  hotel: "Hotel Campo de' Fiori (Rome)",
  hue: 200,
  sampleVersion: 2,
  hotels: [
    {
      name: "Hotel Campo de' Fiori",
      area: 'Historic Center, Rome',
      checkin: 'Oct 5, 2025',    checkinTime: '14:00',
      checkout: 'Oct 10, 2025',  checkoutTime: '11:00',
      nights: 5,
      price: '€180/박',
      address: 'Via del Biscione 6, 00186 Roma, Italy',
      phone: '+39 06 6880 6865',
      confirmation: '',
      amenities: ['Free WiFi', 'Rooftop Terrace', 'Concierge', '24h Front Desk'],
      note: '캄포 데 피오리 광장 도보 1분. 루프탑 테라스에서 로마 파노라마 뷰. 체크인 14시, 체크아웃 11시.',
      rating: 4.4, hue: 20,
    },
    {
      name: 'Soprarno Suites',
      area: 'Oltrarno, Florence',
      checkin: 'Oct 10, 2025',   checkinTime: '15:00',
      checkout: 'Oct 15, 2025',  checkoutTime: '11:00',
      nights: 5,
      price: '€220/박',
      address: 'Via Maggio 35, 50125 Firenze, Italy',
      phone: '+39 055 046 8748',
      confirmation: '',
      amenities: ['Free WiFi', 'Garden Terrace', 'Kitchen', 'Concierge'],
      note: '올트라르노 지구. 폰테 베키오 도보 7분. 체크인 15시, 체크아웃 11시. 조용하고 로컬 분위기.',
      rating: 4.7, hue: 200,
    },
  ],
  days: [
    {
      n: 1, date: 'Oct 5', weekday: 'Sun',
      title: '로마 도착, 스페인 계단',
      titleEn: 'Arrival & Spanish Steps',
      hero: { hue: 20, label: 'ROMA ETERNA' },
      weather: '맑음 · 22°',
      items: [
        { time: '10:30', cat: 'flight', title: '로마 피우미치노 도착',     en: 'Arrive — Rome Fiumicino (FCO)', loc: 'Leonardo da Vinci Airport',
          note: '공항→호텔:\n① Leonardo Express: FCO→Roma Termini (32분, €14)\n② 택시: 고정 요금 €50 (시내 고정 요금제)\n공항 도착→L0 레벨→"Trains to Rome" 표지판\n탑승 전 기계에서 표에 도장(validazione) 필수 — 안 찍으면 벌금' },
        { time: '13:00', cat: 'hotel',  title: '호텔 짐 맡기기',           en: "Hotel Campo de' Fiori", loc: 'Via del Biscione 6',
          note: '체크인 14시 전이면 짐 맡기기\n"Buongiorno, posso lasciare il bagaglio?" (짐 맡길 수 있을까요?)\n루프탑 테라스에서 로마 전망 먼저 감상 (무료)' },
        { time: '13:30', cat: 'food',   title: '점심: 카르보나라 성지',     en: 'Da Enzo al 29 — Carbonara', loc: 'Trastevere',
          note: '로마 정통 카르보나라 맛집\nCacio e Pepe, Carbonara, Amatriciana\n예약 추천 (+39 06 581 2260)\nCoperto(자릿세) €2–3 청구 — 이탈리아 식당 기본', price: '$$' },
        { time: '15:30', cat: 'sight',  title: '스페인 계단',              en: 'Spanish Steps — Trinità dei Monti', loc: 'Piazza di Spagna',
          note: '135개 계단 — 로마 최고의 인증샷 포인트\n계단에 앉아 음식 먹으면 벌금 €400\n계단 아래 베르니니의 바르카차 분수(Fontana della Barcaccia)\n트리니타 데이 몬티 성당 내부 입장 가능 (무료)', duration: '1h' },
        { time: '17:00', cat: 'view',   title: '핀초 언덕 석양',           en: 'Terrazza del Pincio Sunset', loc: 'Viale della Trinità dei Monti',
          note: '석양 시간 30분 전에 핀초 언덕 테라스에 올라가기\n로마 도심 전경과 성 베드로 성당 돔이 한눈에\n무료 입장, 올라가는 길은 스페인 계단 꼭대기에서 연결', duration: '45m' },
        { time: '20:00', cat: 'food',   title: '저녁: 스페인 계단 근처',   en: 'Il Sorpasso / Osteria del Pegno', loc: 'Near Piazza di Spagna',
          note: 'Antipasto: Bruschetta al Pomodoro\nPrimo: Spaghetti alle Vongole (바지락 스파게티)\n식후 젤라또: Fatamorgana (창작 젤라또, Via dei Gracchi)', price: '$$' },
      ],
    },
    {
      n: 2, date: 'Oct 6', weekday: 'Mon',
      title: '콜로세움, 포로 로마노',
      titleEn: 'Colosseum & Roman Forum',
      hero: { hue: 38, label: 'COLOSSEO' },
      weather: '맑음 · 21°',
      items: [
        { time: '08:30', cat: 'sight',  title: '콜로세움',                 en: 'Colosseum (Colosseo)', loc: 'Piazza del Colosseo',
          note: '반드시 사전 예약 필수 (coopculture.it, €16–22)\n줄 없이 시간제 입장\n내부: 2층 아레나 레벨 — 검투사들이 싸운 공간\n콘스탄티누스 개선문(Arco di Costantino)도 감상\n입장권에 포로 로마노·팔라티노 언덕 포함 (당일 사용)', price: '€16–22', duration: '1h 30m' },
        { time: '10:30', cat: 'sight',  title: '포로 로마노 & 팔라티노',   en: 'Roman Forum + Palatine Hill', loc: 'Via Sacra',
          note: '콜로세움 티켓으로 입장\n포로 로마노: 고대 로마 정치·종교·상업 중심지\n비아 사크라(Via Sacra): 로마 황제들의 개선 행진 도로\n팔라티노 언덕: 황제 궁전 터, 전망대에서 포로 로마노 전체 뷰', duration: '2h' },
        { time: '13:00', cat: 'food',   title: '점심: 조각 피자',          en: 'Pizza al Taglio Near Colosseum', loc: 'Near Colosseo',
          note: 'Pizza al Taglio: 무게 달아 파는 로마 조각 피자\n로마 피자는 얇고 바삭한 것이 특징 (나폴리 피자와 다름)\nSupplì Roma: 로마식 라이스볼 (Supplì al Telefono)', price: '$' },
        { time: '14:30', cat: 'walk',   title: '치르코 마시모',            en: 'Circus Maximus', loc: 'Via del Circo Massimo',
          note: '고대 로마 최대 전차 경주장 (25만 명 수용), 지금은 잔디 공원\n아벤티노 언덕 Malta Priory 추천:\n- 열쇠 구멍으로 성 베드로 돔이 보임!\n- 주소: Piazza dei Cavalieri di Malta', duration: '45m' },
        { time: '16:00', cat: 'walk',   title: '트라스테베레',             en: 'Trastevere Evening Stroll', loc: 'Trastevere',
          note: '로마 강 건너편 오래된 서민 동네\n좁은 돌길과 벽화, 오렌지 나무들\n산타 마리아 인 트라스테베레 성당 (12세기 모자이크)\n저녁 7시 이후 현지인들이 식사하러 나옴', duration: '1h 30m' },
        { time: '19:30', cat: 'food',   title: '저녁: 트라스테베레',       en: 'Da Enzo al 29 / Tonnarello', loc: 'Trastevere',
          note: 'Da Enzo al 29: 예약 필수, 정통 로마 파스타\nTonnarello: 야외석, 활기찬 분위기\nAmatriciana (토마토+판체타): 필수 주문\n식후: Fior di Luna 수제 젤라또', price: '$$' },
      ],
    },
    {
      n: 3, date: 'Oct 7', weekday: 'Tue',
      title: '바티칸, 성 베드로 성당',
      titleEn: 'Vatican & St. Peter\'s',
      hero: { hue: 210, label: 'CITTÀ DEL VATICANO' },
      weather: '맑음 · 20°',
      items: [
        { time: '08:00', cat: 'sight',  title: '바티칸 박물관 & 시스티나 예배당', en: 'Vatican Museums + Sistine Chapel', loc: 'Viale Vaticano',
          note: '오픈런 필수 (museivaticani.va, €17–27)\n8시 오픈 30분 전 도착 추천\n관람 순서: 이집트관→지도의 갤러리(120m 복도)→라파엘로의 방→시스티나 예배당\n시스티나 예배당: 미켈란젤로 천장화(천지창조)+제단화(최후의 심판)\n내부 사진 촬영 금지 / 소음 자제 / 복장 규정(어깨+무릎 가리기)\n오디오 가이드 렌탈 추천 (€7)', price: '€17–27', duration: '3h' },
        { time: '12:00', cat: 'food',   title: '점심: 프라티 트라토리아',   en: "Osteria dell'Angelo", loc: 'Prati',
          note: '고정 메뉴(Menù fisso) €18: 샐러드+파스타+메인+와인+물 포함\n매우 알뜰하고 맛있음 — 현지인 단골', price: '$$' },
        { time: '13:30', cat: 'sight',  title: '성 베드로 성당 & 쿠폴라',  en: "St. Peter's Basilica + Dome", loc: 'Piazza San Pietro',
          note: '광장: 베르니니 설계, 284개 기둥\n내부 무료 입장 (복장: 반바지·민소매 금지)\n미켈란젤로의 피에타(Pietà)→청동 발다키노→베드로 묘\n쿠폴라 등반: 엘리베이터 €8 (or 계단만 €6)\n551계단 or 엘베+320계단 — 정상서 로마 360° 뷰', price: '€6–8', duration: '2h' },
        { time: '16:00', cat: 'sight',  title: '카스텔 산탄젤로',          en: "Castel Sant'Angelo", loc: 'Lungotevere Castello',
          note: '하드리아누스 황제 영묘→교황 요새→현재 박물관\n성 천사교(Ponte Sant\'Angelo)의 12 천사 조각 감상\n내부 입장 €14 (외관만 봐도 충분)\n성채 꼭대기에서 성 베드로 대성당+강변 뷰', price: '€14', duration: '1h' },
        { time: '18:00', cat: 'walk',   title: '테베레 강변 아페리티보',   en: 'Lungotevere Aperitivo', loc: 'Tevere River',
          note: '카스텔 산탄젤로에서 강변 산책로를 따라 남쪽으로\n석양 시간대에 테베레강 반영 감상\n강변 노천카페에서 Aperol Spritz 한 잔', duration: '45m' },
        { time: '20:00', cat: 'food',   title: '저녁: 프라티',             en: 'Dinner in Prati', loc: 'Prati',
          note: 'Rigatoni alla Gricia (구안치알레+페코리노)\n또는 Supplì Roma 앞에서 Supplì al Telefono (로마식 라이스볼)', price: '$$' },
      ],
    },
    {
      n: 4, date: 'Oct 8', weekday: 'Wed',
      title: '판테온, 트레비, 피아차 나보나',
      titleEn: 'Pantheon, Trevi & Navona',
      hero: { hue: 15, label: 'FONTANA DI TREVI' },
      weather: '맑음 · 22°',
      items: [
        { time: '09:00', cat: 'sight',  title: '판테온',                   en: 'Pantheon', loc: 'Piazza della Rotonda',
          note: '9시 오픈 — 아침 일찍 가야 줄 짧음\n입장료 €5 (pantheonroma.com 예약 가능)\n콘크리트 돔: 직경=높이=43.3m (완벽한 비율)\n오쿨루스(oculus): 돔 꼭대기 구멍으로 빛 입사\n라파엘로 묘소 + 이탈리아 초대 왕 묘소', price: '€5', duration: '45m' },
        { time: '10:00', cat: 'food',   title: '카페 타차 도로',            en: "Caffè Tazza d'Oro", loc: 'Via degli Orfani 84',
          note: '1946년부터 이어온 전설적인 카페 — 판테온 바로 옆\n에스프레소 서서 마시기 (이탈리아 바 문화)\nGranita di Caffè (커피 그라니타+생크림) 강추\n앉으면 2배 → 스탠딩 바 이용', price: '$' },
        { time: '10:45', cat: 'sight',  title: '피아차 나보나',            en: 'Piazza Navona', loc: 'Piazza Navona',
          note: '고대 로마 경기장 위에 만들어진 타원형 광장\n3개 분수:\n① 베르니니 4대강 분수(나일·갠지스·도나우·라플라타)\n② 무어인 분수\n③ 넵튠 분수\n야외 화가들의 초상화도 로마 정취', duration: '1h' },
        { time: '12:00', cat: 'food',   title: '점심: 캄포 데 피오리 시장', en: "Campo de' Fiori Market", loc: "Campo de' Fiori",
          note: '월~토 오전 시장 (12시~12:30 철거)\n신선한 채소·과일·올리브·치즈\nLa Prosciutteria: 프로슈토·치즈 플레이트 테이크아웃\n포카치아 + 길거리 아티초크', price: '$' },
        { time: '14:30', cat: 'sight',  title: '트레비 분수',              en: 'Fontana di Trevi', loc: 'Piazza di Trevi',
          note: '세계에서 가장 유명한 분수 (1762년)\n등지고 동전 1개: 다시 로마에 온다\n등지고 동전 2개: 사랑이 이루어진다\n아침 7시 전이 가장 한산 (오후는 초만원)', duration: '45m' },
        { time: '16:00', cat: 'shop',   title: '비아 콘도티 명품 거리',    en: 'Via Condotti Stroll', loc: 'Via Condotti',
          note: '구찌·프라다·루이비통·불가리 플래그십\n비아 보르고뇨나: 발렌티노·페라가모\nTax Refund: €154.94 이상 구매 시 IVA 환급 (20–22%)', duration: '1h' },
        { time: '18:30', cat: 'bar',    title: '아페리티보',               en: 'Roman Aperitivo', loc: 'Near Piazza Navona',
          note: 'Aperol Spritz 또는 Negroni 주문 시 무료 안주 제공\n추천: Il Sorpasso (Prati) / Barnum Cafe', price: '$' },
        { time: '20:00', cat: 'food',   title: '저녁: 캄포 데 피오리 근처', en: "Dinner near Campo de' Fiori", loc: 'Historic Center',
          note: 'Da Francesco: 로마식 피자+파스타\nRistorante Roscioli: 최고급 치즈·햄 (예약 필수)\n숙소 도보 1분', price: '$$' },
      ],
    },
    {
      n: 5, date: 'Oct 9', weekday: 'Thu',
      title: '보르게세 갤러리, 로마 마지막 날',
      titleEn: 'Borghese Gallery & Last Day Rome',
      hero: { hue: 90, label: 'VILLA BORGHESE' },
      weather: '맑음 · 21°',
      items: [
        { time: '09:00', cat: 'sight',  title: '보르게세 갤러리',          en: 'Galleria Borghese', loc: 'Piazzale Scipione Borghese 5',
          note: '예약 필수! galleriaborghese.it (€15+예약비 €2)\n2시간 시간제 입장 (9·11·13·15·17시 선택)\n대표 작품:\n① 베르니니 <아폴로와 다프네>: 신이 내린 대리석 조각\n② 베르니니 <페르세포네의 납치>: 손가락이 살을 파고드는 표현\n③ 베르니니 <다비드>: 투석기 쏘는 순간\n④ 카라바조 <아픈 바쿠스>·<과일 바구니>\n입장 전 짐 라커룸에 맡겨야 함 (€1 동전 필요)', price: '€17', duration: '2h' },
        { time: '11:30', cat: 'walk',   title: '빌라 보르게세 공원',       en: 'Villa Borghese Park', loc: 'Villa Borghese',
          note: '갤러리 출구에서 바로 연결\n핀초 언덕(Terrazza del Pincio) 방향 산책\n자전거 대여 €4–5/30min\n공원 내 작은 호수에서 보트 타기도 가능', duration: '1h' },
        { time: '13:00', cat: 'food',   title: '점심',                    en: 'Lunch near Piazza del Popolo', loc: 'Piazza del Popolo',
          note: 'Osteria della Frezza: 앤티파스토 뷔페+파스타\n또는 근처 CONAD 슈퍼마켓에서 간단히', price: '$$' },
        { time: '14:30', cat: 'shop',   title: '이탈리아 수공예 기념품',   en: 'Artisan Souvenirs — Via del Governo Vecchio', loc: 'Via del Governo Vecchio',
          note: '빈티지숍, 수공예 가죽 제품, 도자기\n추천 기념품: 이탈리아산 레더 지갑, 도자기, 올리브오일\n캄포 데 피오리 근처 소규모 공방 탐색', duration: '1h 30m' },
        { time: '18:30', cat: 'view',   title: '캄피돌리오 언덕 야경',    en: 'Capitoline Hill Night View', loc: 'Piazza del Campidoglio',
          note: '미켈란젤로가 설계한 캄피돌리오 광장\n광장 뒤편 테라스에서 포로 로마노 야경\n입장 무료, 야경이 환상적', duration: '45m' },
        { time: '20:30', cat: 'food',   title: '마지막 로마 저녁',         en: 'Last Dinner in Rome', loc: 'Trastevere or Historic Center',
          note: '로마 마지막 밤\nEnoteca Regionale Palatium: 라치오 지역 와인+치즈\nAbbazia: 트라스테베레 현지인 단골\n식후 루프탑 테라스에서 마지막 로마 밤 감상', price: '$$$' },
      ],
    },
    {
      n: 6, date: 'Oct 10', weekday: 'Fri',
      title: '피렌체 이동, 두오모',
      titleEn: 'Travel to Florence & Duomo',
      hero: { hue: 340, label: 'FIRENZE' },
      weather: '맑음 · 19°',
      items: [
        { time: '08:00', cat: 'hotel',  title: '로마 호텔 체크아웃',       en: 'Check out — Rome Hotel', loc: "Hotel Campo de' Fiori",
          note: '체크아웃 11시. 일찍 나가면 짐 맡기기 가능\n기차역까지 택시 이용 (약 €12–15)' },
        { time: '09:00', cat: 'flight', title: '로마 → 피렌체 고속열차',   en: 'Roma Termini → Firenze SMN (Frecciarossa)', loc: 'Roma Termini Station',
          note: 'Frecciarossa(고속열차): 1시간 30분, €29–60\ntrenitalia.com 또는 italotreno.it 사전 예약 시 할인\n피렌체 산타 마리아 노벨라역(SMN) 도착 — 도심 한복판\n역에서 호텔까지 도보 or 택시', price: '€29–60', duration: '1h 30m' },
        { time: '11:00', cat: 'hotel',  title: '피렌체 호텔 체크인',       en: 'Soprarno Suites', loc: 'Via Maggio 35',
          note: '체크인 15시 전이면 짐만 맡기기\n올트라르노(Oltrarno): 강 남쪽, 조용하고 로컬스러운 동네\n폰테 베키오 도보 7분', _hotelRef: 'Soprarno Suites' },
        { time: '12:00', cat: 'food',   title: '점심: 메르카토 첸트랄레',   en: 'Mercato Centrale Florence', loc: "Via dell'Ariento",
          note: '1층: 신선식품 시장 / 2층: 푸드홀\n피렌체 명물: Lampredotto 샌드위치 (소 위장+그린소스)\nNino Zuccon: 리볼리타(Ribollita, 토스카나 수프)\n2층 홀 분위기가 아름다움', price: '$' },
        { time: '14:00', cat: 'sight',  title: '피렌체 두오모',            en: 'Cattedrale di Santa Maria del Fiore', loc: 'Piazza del Duomo',
          note: '브루넬레스키 팔각형 돔(1436년)\nFirenzeCard €29: 돔+박물관+세례당+캄파닐레 통합 입장권\n성당 내부: 무료 입장 (복장 규정 있음)\n돔 등반: 예약 필수, 463계단, 피렌체 360° 뷰\n조토의 종탑(Campanile): 414계단, 두오모 측면 뷰\n산 조반니 세례당: 기베르티의 황금 문(천국의 문) 복제본', price: '€29', duration: '2h' },
        { time: '17:00', cat: 'walk',   title: '피아차 델라 레푸블리카',   en: 'Piazza della Repubblica', loc: 'Piazza della Repubblica',
          note: '피렌체 도심 광장 (옛 로마 포럼 자리)\nCaffè Gilli: 1733년 개업, 역사적인 카페\nVia Calzaiuoli: 두오모~시뇨리아 광장 연결 쇼핑가', duration: '45m' },
        { time: '19:30', cat: 'food',   title: '저녁: 올트라르노',         en: 'Dinner in Oltrarno', loc: 'Oltrarno',
          note: 'Borro Antico: 토스카나 와인과 전통 요리\nIl Magazzino: 현지인이 많은 작은 트라토리아\n추천 와인: Chianti Classico (€12–20/병)', price: '$$' },
      ],
    },
    {
      n: 7, date: 'Oct 11', weekday: 'Sat',
      title: '우피치, 폰테 베키오',
      titleEn: 'Uffizi Gallery & Ponte Vecchio',
      hero: { hue: 300, label: 'UFFIZI' },
      weather: '맑음 · 20°',
      items: [
        { time: '09:00', cat: 'sight',  title: '우피치 갤러리',            en: 'Uffizi Gallery', loc: 'Piazzale degli Uffizi',
          note: '예약 필수 (uffizi.it, €20+예약비 €4)\n2층부터 시작 추천:\n① 보티첼리 <비너스의 탄생>·<봄(Primavera)>\n② 레오나르도 다빈치 <수태고지(Annunciazione)>\n③ 미켈란젤로 <성 가족(Doni Tondo)>\n④ 카라바조 <메두사>\n3층 테라스: 폰테 베키오+아르노강 뷰', price: '€24', duration: '2h 30m' },
        { time: '12:00', cat: 'sight',  title: '피아차 델라 시뇨리아',    en: 'Piazza della Signoria', loc: 'Piazza della Signoria',
          note: '피렌체 야외 조각 박물관\n복제 다비드상 (원본은 아카데미아)\n로지아 데이 란치:\n- 첼리니 <메두사를 든 페르세우스>\n- 잠볼로냐 <사비니 여인들의 납치>', duration: '30m' },
        { time: '12:30', cat: 'food',   title: '점심: 트리파 피오렌티나', en: 'Lampredotto Sandwich', loc: 'Near Mercato Nuovo',
          note: 'Lampredotto 샌드위치: 소 위장+그린소스 — 피렌체 길거리 소울푸드\nMercato Nuovo 행운의 돼지코상 문지르기도 잊지 말기', price: '$' },
        { time: '13:30', cat: 'sight',  title: '폰테 베키오',              en: 'Ponte Vecchio', loc: 'Ponte Vecchio',
          note: '1345년 건설, 피렌체 현존 최고(最古) 다리\n다리 위 금세공품·보석 상점들\n메디치 가문의 바사리 회랑이 위를 지나감\n오후가 사진 찍기 좋음 (서향 조명)\n올트라르노 쪽이 더 한산', duration: '30m' },
        { time: '14:30', cat: 'sight',  title: '보볼리 정원',              en: 'Boboli Gardens', loc: 'Piazza Pitti',
          note: '피티 궁전 뒤편 메디치 가문의 정원 (€10)\n이탈리아 정형식 정원의 정수\n정원 높은 곳에서 피렌체 도시 뷰', price: '€10', duration: '1h' },
        { time: '17:00', cat: 'bar',    title: '아르노 뷰 아페리티보',    en: 'Aperitivo with Arno View', loc: 'Lungarno degli Acciaiuoli',
          note: 'Volpi e l\'Uva: 폰테 베키오 옆, 토스카나 와인 특화\n아르노강 반영이 아름다운 해질 녘', price: '$' },
        { time: '19:30', cat: 'food',   title: '저녁: 피렌체 비스테카',    en: "Buca dell'Orafo", loc: 'Near Ponte Vecchio',
          note: "Buca dell'Orafo: 1945년 개업, 폰테 베키오 바로 옆\n비스테카 알라 피오렌티나(Bistecca alla Fiorentina): 1kg+ T본 스테이크, 레어 서빙, €55/kg\nPappardelle al Cinghiale (멧돼지 라구)", price: '$$$' },
      ],
    },
    {
      n: 8, date: 'Oct 12', weekday: 'Sun',
      title: '아카데미아, 미켈란젤로 광장',
      titleEn: "Accademia & Piazzale Michelangelo",
      hero: { hue: 50, label: 'PIAZZALE MICHELANGELO' },
      weather: '맑음 · 18°',
      items: [
        { time: '08:30', cat: 'sight',  title: '아카데미아 — 다비드',      en: "Galleria dell'Accademia", loc: 'Via Ricasoli 58–60',
          note: '예약 필수 (galleriaaccademiafirenze.it, €12+예약비 €4)\n미켈란젤로의 다비드: 5.17m, 순백 카라라 대리석 (1501–1504)\n감상 팁: 오른손이 왼손보다 크게 — 높은 곳에서 보이도록 의도\n미완성 노예 조각들(Prigioni): 대리석에서 빠져나오려는 형상', price: '€16', duration: '1h 30m' },
        { time: '10:30', cat: 'sight',  title: '산 로렌초 & 메디치 예배당', en: 'Basilica di San Lorenzo + Medici Chapels', loc: 'Piazza di San Lorenzo',
          note: '메디치 가문 교구 성당\n메디치 예배당: 미켈란젤로의 <밤·낮·새벽·황혼> 조각 (€9)\n로렌초 도서관(Biblioteca Medicea Laurenziana): 미켈란젤로 계단 설계', price: '€9', duration: '1h' },
        { time: '12:30', cat: 'food',   title: '점심: 메르카토 첸트랄레',  en: 'Mercato Centrale 2F Food Hall', loc: 'Mercato Centrale',
          note: 'Lampredotto·Trippa·전통 토스카나 파스타\n2층 중앙 홀 분위기가 아름다움', price: '$' },
        { time: '14:30', cat: 'walk',   title: '산 미니아토 알 몬테',     en: 'Basilica di San Miniato al Monte', loc: 'Via delle Porte Sante 34',
          note: '도심에서 도보 25–30분 or 버스 12번\n11세기 로마네스크 양식 — 피렌체 최고(最古) 성당\n그린·화이트 대리석 파사드 (두오모와 유사)\n성당 앞 계단에서 피렌체 전망 감상', duration: '1h' },
        { time: '16:30', cat: 'view',   title: '피아찰레 미켈란젤로 일몰', en: 'Piazzale Michelangelo Sunset', loc: 'Piazzale Michelangelo',
          note: '피렌체 최고의 일몰 포인트 — 절대 필수!\n산 미니아토에서 도보 5분 (계단길)\n두오모·베키오 탑·시뇨리아 광장 파노라마\n일몰 30분 전 도착 추천\n광장 야외 바에서 스프리츠 마시며 감상\n일몰 후 블루아워 야경도 아름다움', duration: '1h 30m' },
        { time: '19:30', cat: 'food',   title: '저녁: 에노테카 와인바',   en: 'Enoteca in Oltrarno', loc: 'Oltrarno',
          note: 'Olive & Co: 올리브오일 바+간단한 요리\nBuca Mario: 1886년 개업, 피렌체 최고령 레스토랑\n추천 와인: Brunello di Montalcino, Vino Nobile di Montepulciano', price: '$$' },
      ],
    },
    {
      n: 9, date: 'Oct 13', weekday: 'Mon',
      title: '아씨시 당일치기',
      titleEn: 'Day Trip to Assisi',
      hero: { hue: 160, label: 'ASSISI' },
      weather: '맑음 · 17°',
      items: [
        { time: '07:30', cat: 'flight', title: '피렌체 → 아씨시',         en: 'Train: Firenze SMN → Assisi', loc: 'Firenze Santa Maria Novella',
          note: 'Firenze SMN → Assisi역(Santa Maria degli Angeli): 약 2시간\n페루자(Perugia) 또는 폴리뇨(Foligno) 경유\n기차 예약: trenitalia.com\n아씨시역→구시가지: 버스 C (€1.30, 약 15분)\n구시가지 버스 종점 하차 → 도보', price: '€20–35', duration: '2h' },
        { time: '10:00', cat: 'sight',  title: '성 프란치스코 대성당',    en: "Basilica di San Francesco d'Assisi", loc: "Piazza Inferiore di S. Francesco",
          note: 'UNESCO 세계유산\n하부 성당(Lower Basilica): 치마부에의 프레스코화, 성 프란치스코 무덤 (지하 크립트)\n상부 성당(Upper Basilica): 조토의 <성 프란치스코의 생애> 28장면 — 이탈리아 미술사의 전환점\n복장 규정: 소매+무릎 가리기 필수\n입장 무료', duration: '1h 30m' },
        { time: '12:00', cat: 'walk',   title: '아씨시 구시가지',         en: 'Assisi Medieval Town', loc: 'Assisi Historic Center',
          note: '핑크빛 석회암(pietra rosata di Assisi)으로 만들어진 중세 마을\n피아차 델 코무네: 1세기 로마 미네르바 신전이 남아있음\n좁은 골목 탐색 — 공방과 소품 상점', duration: '1h' },
        { time: '13:30', cat: 'food',   title: '점심: 움브리아 요리',     en: 'Trattoria Pallotta', loc: 'Assisi',
          note: 'Strangozzi al tartufo (트뤼플 파스타)\nPorchetta 샌드위치 — 길거리 음식\n움브리아 와인: Sagrantino, Grechetto', price: '$$' },
        { time: '15:00', cat: 'sight',  title: '산타 키아라 대성당',      en: 'Basilica di Santa Chiara', loc: 'Piazza Santa Chiara',
          note: '성녀 클라라의 성당 (핑크·화이트 줄무늬 파사드)\n성녀 클라라 유해 (지하 크립트)\n성당 앞 광장에서 움브리아 평원 뷰', duration: '45m' },
        { time: '16:00', cat: 'view',   title: '로카 마조레 성채',        en: 'Rocca Maggiore', loc: 'Via della Rocca',
          note: '중세 성채 (€3.50)\n성벽 위에서 아씨시+움브리아 계곡 파노라마\n구시가지에서 도보 20분 (가파름, 편한 신발 필수)', price: '€3.50', duration: '1h' },
        { time: '17:30', cat: 'flight', title: '피렌체로 귀환',           en: 'Return to Florence', loc: 'Assisi → Firenze SMN',
          note: '버스 C → 아씨시역 → 기차로 피렌체 귀환 (2시간)\n피렌체 도착 예상 19:30~20:00', duration: '2h' },
        { time: '20:00', cat: 'food',   title: '저녁: 간단히',            en: 'Light Dinner — Oltrarno', loc: 'Oltrarno',
          note: '아씨시 당일치기 후 피곤하므로 간단히\n호텔 근처 피자 al taglio 또는 Il Santo Bevitore 예약', price: '$' },
      ],
    },
    {
      n: 10, date: 'Oct 14', weekday: 'Tue',
      title: '산타 크로체, 마지막 피렌체',
      titleEn: 'Santa Croce & Last Florence',
      hero: { hue: 55, label: 'SANTA CROCE' },
      weather: '구름 조금 · 17°',
      items: [
        { time: '09:30', cat: 'sight',  title: '산타 크로체 성당',        en: 'Basilica di Santa Croce', loc: 'Piazza di Santa Croce',
          note: '이탈리아 위인들의 판테온 (€8)\n미켈란젤로·갈릴레오·마키아벨리·로시니 무덤\n조토의 프레스코화 (바르디·페루치 예배당)\n브루넬레스키 설계 파치 예배당 (완벽한 비례)\n광장에서 성당 정면이 아름답게 보임', price: '€8', duration: '1h 30m' },
        { time: '11:30', cat: 'walk',   title: '산탐브로조 시장',         en: "Mercato di Sant'Ambrogio", loc: 'Piazza Lorenzo Ghiberti',
          note: '피렌체 현지인 일상 시장 (관광객 거의 없음)\n신선 채소·과일·치즈·살루미\n내부 Trattoria da Rocco: €5–8 파스타, 현지인 소울푸드', duration: '1h' },
        { time: '13:00', cat: 'food',   title: '점심: 트라토리아 다 로코', en: 'Trattoria da Rocco', loc: "Mercato di Sant'Ambrogio",
          note: '매일 바뀌는 메뉴 (칠판에 표시)\n€6–8에 파스타+세컨드+와인\n포리나타(Farinata): 병아리콩 팬케이크', price: '$' },
        { time: '14:30', cat: 'shop',   title: '가죽 공예 쇼핑',          en: 'Artisan Leather — Scuola del Cuoio', loc: 'Via San Giuseppe 5r',
          note: '산타 크로체 성당 뒤편 가죽 학교\n장인이 직접 만드는 가죽 제품 (지갑·벨트·백)\n피렌체 = 이탈리아 가죽 공예의 수도\nRoberta Firenze: 수제 금박 문구류', duration: '1h 30m' },
        { time: '17:00', cat: 'view',   title: '피아찰레 미켈란젤로 황혼', en: 'Piazzale Michelangelo — Dusk', loc: 'Piazzale Michelangelo',
          note: '마지막으로 보는 피렌체 황혼\n블루아워(blue hour): 일몰 후 20–30분, 하늘 색이 가장 아름다운 시간\n도시 불빛이 켜지는 야경이 일몰보다 더 황홀', duration: '1h' },
        { time: '19:00', cat: 'food',   title: '마지막 피렌체 저녁',       en: 'Final Dinner — Il Santo Bevitore', loc: 'Oltrarno',
          note: '예약 필수, 올트라르노 최고 레스토랑\nPappardelle al Cinghiale (야생 멧돼지 라구)\nBistecca alla Fiorentina (T본 스테이크 최소 1kg)\nChianti Classico Gran Selezione\n식후: 아르노 강변 마지막 야경 산책', price: '$$$' },
      ],
    },
    {
      n: 11, date: 'Oct 15', weekday: 'Wed',
      title: '출발',
      titleEn: 'Departure',
      hero: { hue: 220, label: 'ARRIVEDERCI' },
      weather: '맑음 · 16°',
      items: [
        { time: '08:00', cat: 'hotel',  title: '호텔 체크아웃',            en: 'Check out — Soprarno Suites', loc: 'Via Maggio 35',
          note: '체크아웃 11시\n피렌체 공항(FLR, Peretola): 택시 €20–25, 15분\n피사 공항(PSA): 피렌체 SMN→피사 첸트랄레 기차 50분+공항버스 10분\n짐 많으면 택시 추천' },
        { time: '09:00', cat: 'food',   title: '마지막 이탈리아 조식',     en: 'Last Cornetto e Caffè', loc: 'Pasticceria Nencioni',
          note: '이탈리아 바에서 마지막 에스프레소\nCornetto: 살구잼(albicocca) 또는 크레마(커스터드) 필링\nCappuccino는 아침에만 (오후엔 에스프레소 문화)\n마지막 인사: "Grazie! Arrivederci!" (감사합니다! 또 만나요!)', price: '$' },
        { time: '10:00', cat: 'shop',   title: '마지막 기념품',            en: 'Last Souvenirs Near SMN', loc: 'Near Santa Maria Novella Station',
          note: 'Officina Profumo-Farmaceutica di Santa Maria Novella: 1612년 약방, 세계 최고 향수·허브 제품\n슈퍼마켓 기념품: 피렌체 올리브오일, 트뤼플 소스, 파스타\nBaci Perugina: 페루자 산 헤이즐넛 초콜릿', duration: '1h' },
        { time: '12:00', cat: 'flight', title: '공항 출발',               en: 'Departure — FLR or PSA Airport', loc: 'Florence / Pisa Airport',
          note: '출국 2시간 전 도착 추천\nBuon viaggio! (좋은 여행 되세요!)' },
      ],
    },
  ],

  prep: {
    checklist: [
      '항공권 예매', '숙소 예매 (로마 5박+피렌체 5박)',
      '우피치·아카데미아 사전 예약', '바티칸 박물관 예약',
      '보르게세 갤러리 예약', '콜로세움 예약',
      '로마↔피렌체 기차 예약', '피렌체↔아씨시 기차 예약',
      '짐 싸기', '로밍/유심 준비', '여행자 보험',
      '택시 앱 설치 (Free Now / itTaxi)',
      '구글 오프라인 지도 다운로드 (로마·피렌체·아씨시)',
    ],
    docs: [
      '왕복 항공권 e-ticket',
      '호텔 예약 확인서 (로마+피렌체)',
      '박물관 예약 확인서',
      '기차 예약 확인서',
      '여행자 보험 증서',
      '여권 (유효기간 6개월 이상)',
    ],
    pack: [
      '걷기 편한 신발 필수 (자갈길 많음)',
      '보조 배터리',
      '얇은 가디건 (성당 내부 복장용)',
      '선크림',
      '소형 우산 or 우비',
      '재사용 가방 (시장 쇼핑용)',
      '물통 (로마 나스코네 수돗물 이용 가능)',
    ],
  },

  food: [
    { cat: '🍝 Pasta',   name: 'Carbonara (로마)',         detail: '달걀·페코리노·구안치알레·후추 — 크림 없음이 정통', price: '€12–16', note: 'Da Enzo al 29 추천' },
    { cat: '🍝 Pasta',   name: 'Cacio e Pepe',            detail: '치즈+후추만으로 완성, 단순함의 극치',             price: '€10–14', note: '로마 3대 파스타' },
    { cat: '🍝 Pasta',   name: 'Amatriciana',             detail: '토마토+구안치알레, 매콤달콤',                     price: '€12–16', note: '로마 3대 파스타' },
    { cat: '🍝 Pasta',   name: 'Pappardelle al Cinghiale', detail: '넓은 파파르델레 + 야생 멧돼지 라구',             price: '€14–18', note: '피렌체·토스카나 명물' },
    { cat: '🍝 Pasta',   name: 'Strangozzi al Tartufo',   detail: '움브리아 수제 파스타 + 트뤼플',                   price: '€16–22', note: '아씨시·움브리아 명물' },
    { cat: '🥩 Meat',    name: 'Bistecca alla Fiorentina', detail: '피렌체 T본 스테이크 1kg+, 레어, €55/kg',         price: '$$$$',   note: "Buca dell'Orafo 추천" },
    { cat: '🥩 Meat',    name: 'Lampredotto',             detail: '피렌체 소 위장 샌드위치 — 현지인 소울푸드',        price: '€5–8',   note: '메르카토 첸트랄레' },
    { cat: '🥩 Meat',    name: 'Porchetta',               detail: '아씨시 광장 허브 로스트 통돼지 샌드위치',          price: '€5',     note: '아씨시 피아차' },
    { cat: '🍕 Pizza',   name: 'Pizza al Taglio',         detail: '무게 달아 파는 로마 조각 피자',                   price: '€4–8',   note: '로마 전역' },
    { cat: '🍨 Gelato',  name: '정통 수제 젤라또',         detail: '표면 평평+덮개 없는 것이 수제 (소프트아이스크림 아님)', price: '€2.5–4', note: 'Fatamorgana(로마), Gelateria dei Neri(피렌체)' },
    { cat: '☕ Coffee',  name: 'Espresso al Banco',       detail: '서서 마시면 €1.20, 앉으면 €2.50+',               price: '€1.20',  note: '카페 타차 도로 추천' },
    { cat: '☕ Coffee',  name: 'Granita di Caffè',        detail: '커피 그라니타+생크림 — 로마 여름 특선',            price: '€3–4',   note: '카페 타차 도로 한정' },
    { cat: '🍷 Wine',    name: 'Chianti Classico',        detail: '토스카나 대표 레드와인, 산조베제 품종',            price: '€12–20', note: '피렌체 에노테카' },
    { cat: '🍷 Wine',    name: 'Brunello di Montalcino',  detail: '이탈리아 최고급 와인 중 하나',                    price: '€30–80', note: '특별한 날에' },
    { cat: '🍷 Wine',    name: 'Sagrantino di Montefalco', detail: '움브리아 토착 품종, 타닌 강렬',                  price: '€15–25', note: '아씨시·움브리아' },
    { cat: '🍹 Drink',   name: 'Aperol Spritz',          detail: 'Aperol+프로세코+소다, 이탈리아 아페리티보 필수',   price: '€7–12',  note: '저녁 식사 전 필수' },
    { cat: '🧁 Pastry',  name: 'Cornetto e Cappuccino',  detail: '이탈리아 아침: 크루아상+카푸치노 서서 마시기',     price: '€3–5',   note: '아침에만 카푸치노' },
  ],
  budget: {
    entries: [
      // ── 수입 ──────────────────────────────────────────────────────
      { id:'r01', type:'in',  amount:2500000, currency:'KRW', cat:'환전',   note:'출발 전 환전 €1,600',      date:'Oct 4',  scope:'personal' },

      // ── 교통 ──────────────────────────────────────────────────────
      { id:'r02', type:'out', amount:1680000, currency:'KRW', cat:'교통',   note:'인천 → 로마 FCO 왕복',     date:'Oct 5',  scope:'personal' },
      { id:'r03', type:'out', amount:8,       currency:'EUR', cat:'교통',   note:'FCO 공항 → 테르미니 기차',  date:'Oct 5',  scope:'personal' },
      { id:'r04', type:'out', amount:18,      currency:'EUR', cat:'교통',   note:'로마 지하철 10회권',        date:'Oct 5',  scope:'personal' },
      { id:'r05', type:'out', amount:11,      currency:'EUR', cat:'교통',   note:'로마 → 아씨시 기차',        date:'Oct 10', scope:'personal' },
      { id:'r06', type:'out', amount:19,      currency:'EUR', cat:'교통',   note:'아씨시 → 피렌체 기차',      date:'Oct 11', scope:'personal' },
      { id:'r07', type:'out', amount:35,      currency:'EUR', cat:'교통',   note:'피렌체 → FCO 공항 이타로',  date:'Oct 14', scope:'personal' },

      // ── 숙박 ──────────────────────────────────────────────────────
      { id:'r08', type:'out', amount:1190,    currency:'EUR', cat:'숙박',   note:'호텔 아르테미데 로마 7박',  date:'Oct 5',  scope:'personal' },
      { id:'r09', type:'out', amount:210,     currency:'EUR', cat:'숙박',   note:'아씨시 B&B 1박',           date:'Oct 10', scope:'personal' },
      { id:'r10', type:'out', amount:590,     currency:'EUR', cat:'숙박',   note:'피렌체 호텔 3박',           date:'Oct 11', scope:'personal' },

      // ── 식비 ──────────────────────────────────────────────────────
      { id:'r11', type:'out', amount:28,      currency:'EUR', cat:'식비',   note:'트라스테베레 파스타+와인',  date:'Oct 6',  scope:'personal' },
      { id:'r12', type:'out', amount:14,      currency:'EUR', cat:'식비',   note:'나보나 젤라또+에스프레소', date:'Oct 7',  scope:'personal' },
      { id:'r13', type:'out', amount:45,      currency:'EUR', cat:'식비',   note:'피렌체 비스테카 피오렌티나', date:'Oct 12', scope:'personal' },
      { id:'r14', type:'out', amount:9,       currency:'EUR', cat:'식비',   note:'코르네토+카푸치노 (매일)',  date:'Oct 8',  scope:'personal' },

      // ── 관광 ──────────────────────────────────────────────────────
      { id:'r15', type:'out', amount:18,      currency:'EUR', cat:'관광',   note:'콜로세움+포로로마노 입장',  date:'Oct 6',  scope:'personal' },
      { id:'r16', type:'out', amount:20,      currency:'EUR', cat:'관광',   note:'바티칸 박물관+시스티나',    date:'Oct 8',  scope:'personal' },
      { id:'r17', type:'out', amount:12,      currency:'EUR', cat:'관광',   note:'우피치 미술관 (피렌체)',    date:'Oct 12', scope:'personal' },
      { id:'r18', type:'out', amount:8,       currency:'EUR', cat:'관광',   note:'두오모 전망대 (피렌체)',    date:'Oct 13', scope:'personal' },

      // ── 쇼핑 ──────────────────────────────────────────────────────
      { id:'r19', type:'out', amount:68,      currency:'EUR', cat:'쇼핑',   note:'가죽 지갑 (산 로렌초 시장)', date:'Oct 12', scope:'personal' },
      { id:'r20', type:'out', amount:24,      currency:'EUR', cat:'쇼핑',   note:'올리브오일+트러플소스 기념품', date:'Oct 13', scope:'personal' },
    ],
  },
};
